# ---- Stage 1: The "Builder" ----
# We use a full Node image here because we need build tools and system libraries (for Prisma/Playwright)
FROM node:20 AS builder

WORKDIR /usr/src/app

# (Optional but recommended) Install Playwright system dependencies if you run tests here
# RUN apt-get update && apt-get install -y --no-install-recommends libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgtk-3-0 libgbm1 libasound2

# Copy package manifests and install ALL dependencies (including dev)
COPY package*.json ./
RUN npm install

# Copy the rest of the application source code
COPY . .

# Generate the Prisma Client (if you are using it)
# It needs to be generated before the build
RUN npx prisma generate

# Run the SvelteKit build. This now has access to devDependencies and the source code.
RUN npm run build

# Prune devDependencies to prepare for the production copy.
# This makes the node_modules copy in the next stage smaller.
RUN npm prune --omit=dev


# ---- Stage 2: The Final "Production" Image ----
# Start from a clean, small, and secure Alpine Linux base image
FROM node:20-alpine AS final

# Set the environment to production
ENV NODE_ENV=production

WORKDIR /app

# Copy the pruned node_modules from the builder stage
COPY --from=builder /usr/src/app/node_modules ./node_modules

# Copy the built SvelteKit application from the builder stage
COPY --from=builder /usr/src/app/build ./build

# Copy the package.json. It's good practice to have it.
COPY --from=builder /usr/src/app/package.json ./package.json

# Copy the generated Prisma client and schema if it's needed at runtime
COPY --from=builder /usr/src/app/prisma ./prisma

# Set your environment variables (these are better managed by your deployment platform, e.g., Terraform variables)
ENV PUBLIC_URL="example.com"
ENV PROTOCOL_HEADER='x-forwarded-proto'
ENV HOST_HEADER='x-forwarded-host'
ENV ORIGIN='https://localhost:3002'
ENV API_URL='http://host.docker.internal:8000'
ENV DEBUG=true
ENV PORT=3000

# Expose the port the SvelteKit app will run on (default for adapter-node is 3000)
EXPOSE 3000

# The command to start the app.
# This runs the server generated by SvelteKit's adapter-node, NOT your old index.js
CMD [ "node", "build" ]